<a href="https://colab.research.google.com/github/Wejdan999/T55/blob/main/Copy_of_SVD_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**SVD**

#import libraries

In [1]:
import numpy as np

#Load the tabular dataset :

dataset :


    [1, 2, 1, 0, 4],

    [2, 3, 4, 0, 2],

    [3, 1, 1, 0, 5],

    [4, 0, 2, 5, 0],

    [5, 4, 0, 1, 2]


In [2]:
dataset = np.array([[1, 2, 1, 0, 4],

[2, 3, 4, 0, 2],

[3, 1, 1, 0, 5],

[4, 0, 2, 5, 0],

[5, 4, 0, 1, 2]])

#Perform Singular Value Decomposition (SVD)


In [3]:
U, s, VT = np.linalg.svd(dataset)

# Extract the singular values and vectors

In [4]:
singular_values = np.diag(s)
left_singular_vectors = U
right_singular_vectors = VT.T


# Perform dimensionality reduction by selecting top k singular values and vectors


In [5]:
k = 4
reduced_dataset = np.dot(np.dot(left_singular_vectors[:, :k], singular_values[:k, :k]), right_singular_vectors[:, :k].T)

# Print the original and reduced datasets


In [6]:
print("Original Dataset:")
print(dataset)
print("\nReduced Dataset:")
print(reduced_dataset)

Original Dataset:
[[1 2 1 0 4]
 [2 3 4 0 2]
 [3 1 1 0 5]
 [4 0 2 5 0]
 [5 4 0 1 2]]

Reduced Dataset:
[[ 1.51747498e+00  1.55874271e+00  1.19757748e+00 -5.17632763e-01
   3.84336465e+00]
 [ 1.87733335e+00  3.10459937e+00  3.95316456e+00  1.22704056e-01
   2.03713017e+00]
 [ 2.65747194e+00  1.29207789e+00  8.69219125e-01  3.42632498e-01
   5.10368038e+00]
 [ 4.08023363e+00 -6.84162057e-02  2.03063406e+00  4.91974190e+00
  -2.42860501e-02]
 [ 5.00557730e+00  3.99524417e+00  2.12947231e-03  9.94421001e-01
   1.99831180e+00]]


#**Well done :)**